language: node_js
node_js:
    - "8"

before_install:
    - npm i -g spellchecker-cli # installs spellchecker

cache:
    directories:
        - "node_modules"
    


jobs:
    script: ./spellcheck.sh
